version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_api
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - product-api

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - product-api

networks:
  product-api:
    driver: bridge